$ConfirmPreference = "None"
$ErrorActionPreference = "SilentlyContinue"
$DebugPreference = "SilentlyContinue"
$InformationPreference = "SilentlyContinue"
$ProgressPreference = "SilentlyContinue"
$WarningPreference = "SilentlyContinue"
$VerbosePreference = "SilentlyContinue"

Param(
    [parameter(mandatory = $true)]$src,
    [parameter(mandatory = $true)]$dst
)

robocopy $src $dst /COPYALL /MIR /FFT /B /R:0 /W:1 /NP /NDL /NFL
# SIG # Begin signature block
# MIIIRQYJKoZIhvcNAQcCoIIINjCCCDICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUxCz1/25gcynv/9cTd0tAPzhM
# AmKgggW7MIIFtzCCBJ+gAwIBAgITbQAAAXL0J/ozOTINYAABAAABcjANBgkqhkiG
# 9w0BAQUFADA8MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZ
# FgNuYWMxDjAMBgNVBAMTBW5hY0NBMB4XDTIwMDcwMjAwMTg0MVoXDTIxMDcwMjAw
# MTg0MVowgasxFTATBgoJkiaJk/IsZAEZFgVsb2NhbDETMBEGCgmSJomT8ixkARkW
# A25hYzESMBAGA1UECwwJTkFD56S+5YaFMRUwEwYDVQQLDAzjg6bjg7zjgrbjg7wx
# FTATBgNVBAsMDOeuoeeQhuacrOmDqDEjMCEGA1UECwwaSVTjgr3jg6rjg6Xjg7zj
# grfjg6fjg7Ppg6gxFjAUBgNVBAMMDeWwj+W9oiDnpZDntIAwggEiMA0GCSqGSIb3
# DQEBAQUAA4IBDwAwggEKAoIBAQDnF47Fy0myOriHqzwqfo2o3d4QSIToP4DJCQqG
# PPWXpj57e1SqwQ+8xbNs6PMpV8QpGuJQgkMCdjIqV11DehDfzWq51Qb5Lt9tXmc2
# HKBWweAPjf9OUSBlznuv3s064z8uBuxb0j2REkFLKlD2m5SeJizcXs/rCIcerCVI
# x76sgrU7kCyNCcSK2Pt7zRoMElXZsg577YSI4Jy7fffPWljUMLFefUjoXKlPQbqz
# vGoOzEZuZMqd3h/BPnTZVt/P4rL11BeBzCODewXyYUmiQX61pNnCqazpKE8Ooy4r
# nFFafXBMoLA0rUdU5NyMCdtHadk6VSN2RXcFIG1BnJCMzHPRAgMBAAGjggJAMIIC
# PDAlBgkrBgEEAYI3FAIEGB4WAEMAbwBkAGUAUwBpAGcAbgBpAG4AZzATBgNVHSUE
# DDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFKfMwRviK2Rc
# ZxzazsONg+rZdS3jMB8GA1UdIwQYMBaAFHobtNrhJ3mOHC8UzhlVsq8TPZCZMIHD
# BgNVHR8EgbswgbgwgbWggbKgga+GgaxsZGFwOi8vL0NOPW5hY0NBKDEpLENOPU5B
# Q0FEMSxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2Vydmlj
# ZXMsQ049Q29uZmlndXJhdGlvbixEQz1uYWMsREM9bG9jYWw/Y2VydGlmaWNhdGVS
# ZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBv
# aW50MIG1BggrBgEFBQcBAQSBqDCBpTCBogYIKwYBBQUHMAKGgZVsZGFwOi8vL0NO
# PW5hY0NBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2
# aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPW5hYyxEQz1sb2NhbD9jQUNlcnRpZmlj
# YXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTAwBgNV
# HREEKTAnoCUGCisGAQQBgjcUAgOgFwwVb2dhdGEueXV1a2lAbmFjLmxvY2FsMA0G
# CSqGSIb3DQEBBQUAA4IBAQAei9yofGpcEpUhxVyva9UfJUAQV28QXMxRBFObWlIy
# LaM8dPKGgq5ssBVgbGZ6A8Jfhjoc7QMZGhi48Y3XX7yaUx+YzZfH0fFY7gQNp9LP
# 8Un6whu7Sm66IVpky3AY+cOE7eStS81XgSzro0cRIikqJE/Z1utIoR1lm7tNGMBP
# r/BBxb6jaVBa/s8W7E6gmibgPovyMaUjPLiuRWyOOzrKmBf9vl6nI0unAjW5v+Z6
# mq4JBXO1pPSktXS5TallU47TKonuVocT7q2a+MJrogHZn+uRNQhdNI4l+JnQJ9W7
# f4B4H7SIMGYff5oa7xBHYM+P0wePBNynIXjxsbOJPkyaMYIB9DCCAfACAQEwUzA8
# MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNuYWMxDjAM
# BgNVBAMTBW5hY0NBAhNtAAABcvQn+jM5Mg1gAAEAAAFyMAkGBSsOAwIaBQCgeDAY
# BgorBgEEAYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3
# AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEW
# BBR4lhYe+FhSAZcn6qVNrObX3qqwIjANBgkqhkiG9w0BAQEFAASCAQBgV8iWACt9
# VF0uS5GwMDTzhbNNOnTMUZJ/wzfbr7nylCuE6k+TWEqJnYxacAPRdaN8+XyuryAm
# ELnyh9K0nlvS9/wo6Mi8PDkv9W9a4M45cJqwLvTsAKt8rVOWFBaAyR0gD3E1Sguj
# 40SS1TlDXiFUuzmmGBgMifB+GpBis45NkgrMRwERFd4vRrwBtk6OVDo4l32FUKaB
# txguIwlmeG8e4LjEf6hCRQvhBXeL86fI2yQXSPza3N452ihFbjpaIBUI+Ma+09k4
# p5Db9aOz7TQJDrtLQf8fTbVwbb18AtgKeeIOaRG8T5dIkBI5Tb3vCP7Wdrh6lWKr
# 7SjV8Z00BBwU
# SIG # End signature block
